# Generated by Django 5.2.4 on 2025-08-02 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Janeiro_Branco', '0002_recomendacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegiaoAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.CharField(blank=True, max_length=50)),
                ('site', models.URLField(blank=True)),
                ('tipo_atendimento', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('AMBOS', 'Ambos')], default='PRESENCIAL', max_length=10)),
                ('forma_pagamento', models.CharField(choices=[('GRATUITO', 'Gratuito'), ('SOCIAL', 'Preço Social'), ('INTEIRO', 'Preço Inteiro')], default='INTEIRO', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('regiao_administrativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locais', to='Janeiro_Branco.regiaoadministrativa')),
            ],
        ),
    ]
